# Generated by Django 3.1.5 on 2021-05-03 10:55

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('design', models.TextField()),
                ('usability', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('link', models.URLField(max_length=70)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('technologies', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
